# Generated by Django 6.1.1 on 2026-09-26 08:18

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify_days', models.CharField(default='7,3,1', max_length=40, verbose_name='أيام التنبيه قبل الاستحقاق (مفصولة بفاصلة)')),
                ('notifications_enabled', models.BooleanField(default=True, verbose_name='تفعيل التنبيهات')),
                ('late_daily', models.BooleanField(default=True, verbose_name='تنبيه يومي للمتأخرين')),
                ('dark_mode', models.BooleanField(default=False, verbose_name='الوضع الليلي')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='الاسم')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='رقم الهاتف')),
                ('farm_name', models.CharField(blank=True, max_length=150, verbose_name='اسم المزرعة / الشركة')),
                ('address', models.CharField(blank=True, max_length=250, verbose_name='العنوان')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='اسم الشريحة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FeedTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='تاريخ السحب')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='وقت السحب (اختياري)')),
                ('feed_type', models.CharField(blank=True, max_length=120, verbose_name='نوع العلف')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='الكمية')),
                ('unit', models.CharField(choices=[('طن', 'طن'), ('كجم', 'كجم'), ('شيكارة', 'شيكارة')], default='طن', max_length=10, verbose_name='الوحدة')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='سعر الوحدة')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14)),
                ('vehicle_number', models.CharField(blank=True, max_length=40, verbose_name='رقم السيارة (اختياري)')),
                ('invoice_number', models.CharField(blank=True, max_length=60, verbose_name='رقم إذن/فاتورة (اختياري)')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('due_date', models.DateField(editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='feed.customer')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='feed.region', verbose_name='الشريحة'),
        ),
    ]
